### ISSUE TITLE
Enhancement Request: Check if file is open before moving tiers

### ISSUE THREAD

**Issue by inthebrilliantblue** [45Drives/autotier#10]
Reading the code I cant help but notice that there is no checking for open file handles before moving files (Atleast I think, my c++ is pretty rusty). Obviously this is bad and needs to be addressed.

Something simple like checking the output of is_open before moving should be quick enough.

But I would hazard a guess that additional code would be needed to recalculate WATERMARK usage if a file is currently locked.

**Comment by inthebrilliantblue** [comment]
Just to verify and see if this is an issue, I ran:

`dd if=/dev/urandom of=/t1/1.dat bs=1M count=10000`

And while that is running, called autotier with WATERMARK=0 on /t1. Which tosses this error after trying to move 1.dat off /t1 to /t2:

> Copy failed!
> terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>   what():  boost::filesystem::create_symlink: File exists: "/t2/1.dat", "/t1/1.dat"
> Aborted (core dumped)

**Comment by joshuaboud** [comment]
I have researched this issue and it seems that it would be very difficult to see if a file is open by another process in a Linux system. The result of is_open only states whether or not a file was successfully opened by the calling process, not if that file is open by any other process. File locks are only advisory so the opening process must have this feature implemented, which is rare. The only possible option I have found is parsing the file descriptors somewhere in /proc but this is a very messy solution. I will keep this issue open for now to see if anyone else has any ideas.

**Comment by joshuaboud** [comment]
I was able to add this feature by having it execute `lsof <file path>` and using the exit status to determine whether or not the file was open (exit == 1: file not open, exit == 0, file open by another process). This adds `lsof` as a dependency but this program is widely available.

**Comment by inthebrilliantblue** [comment]
> I was able to add this feature by having it execute `lsof <file path>` and using the exit status to determine whether or not the file was open (exit == 1: file not open, exit == 0, file open by another process). This adds `lsof` as a dependency but this program is widely available.

As for having lsof as a dependency, perhaps code could be added to check for if lsof is available?

**Comment by joshuaboud** [comment]
The RPM package for installing on Centos has lsof as a required package so it will automatically be installed. For use on other distributions or if lsof is uninstalled, there is code to catch the error where execlp() on lsof fails - it reports to the user that lsof may not be installed but continues without aborting. Right now, if lsof is not installed, autotier defaults to moving the file anyway, open or not.
