### ISSUE TITLE
Crashes with Recursive Symlinks

### ISSUE THREAD

**Issue by Krutonium** [45Drives/autotier#23]
So I was curious and tried to see if I could make this work with my home directory, and I ran into a blocking issue - autotier will crash as it explores my home directory, in my .wine directory specifically, recursively entering a directory over and over.

**Comment by Krutonium** [comment]
(It crashes after enough iterations of this)

**Comment by joshuaboud** [comment]
Thanks for pointing this out. Fixed by making sure boost::filesystem never tries to dereference symlinks. Fixed with #27
