### ISSUE TITLE
use autotier on existing drive

### ISSUE THREAD

**Issue by smallzzy** [45Drives/autotier#40]
I tried to apply autotier on existing drive as a solution for expanding volume.
But when I run `ls`, it will report `cannot open directory '.'`.

I was able to resolve the problem by rsync the folder structure to the new tier. And it seems to be work fine.

I wonder if this mode of operation is supported? Maybe autotier can detect the missing folder and create it automatically. Or can we at least have some document on this?

**Comment by smallzzy** [comment]
Well, it is not 100% working. When I do `ls` in some folders, there might be duplicated entries.

**Comment by joshuaboud** [comment]
Hi @smallzzy,
Can you attach your autotier configuration file and the command/fstab entry you used to mount? Along with this, which Linux distribution are you using?
Thanks

**Comment by smallzzy** [comment]
I am using Ubuntu 20.04 and the 1.1.3 release.

The fstab has the following content
```
/dev/disk/by-uuid/46da36ee-d96a-435e-b58b-8e85d8420012 /mnt/t1 ext4 defaults 0 2
/dev/disk/by-uuid/76d28e01-5fbd-4eda-88b8-ba0ee4743d2c /mnt/t2 ext4 defaults 0 2
# /usr/bin/autotierfs /home fuse allow_other,default_permissions 0 0
```

And the autotier config is this:
```
# autotier config
[Global]                       # global settings
Log Level = 2                  # 0 = none, 1 = normal, 2 = debug
Tier Period = 600             # number of seconds between file move batches

[Tier 1]
Path = /mnt/t1
Quota = 70%

[Tier 2]
Path = /mnt/t2
Quota = 100%
```

t1 is the original drive that I have. I added t2 to form an autotier. t2 was empty at the beginning of the operation.
After starting autotierfs with `autotierfs /home -v -o allow_other,default_permissions`, `ls` will report `cannot open directory '.' `

So, I sync the folder structure from t1 to t2 with `rsync -a --include '*/' --exclude '*' /mnt/t1/ /mnt/t2/`. And ls will no longer report any issue. But some folder will be listed twice instead.

**Comment by joshuaboud** [comment]
You copied everything from t1 to t2, that is why you're seeing duplicate entries. Also, you really should not mount autotier on `/home`, as now you won't be able to access your home directory until you unmount it. Sometimes if autotierfs crashes, you will see `cannot open directory '.'`, so unmount with `umount autotier -l && killall autotierfs` before trying to mount again. Autotier really wasn't designed to simply expand storage across multiple disks, and is meant to be used for tiered storage. [Mergerfs](https://github.com/trapexit/mergerfs) may be a better solution for what you're trying to do.

**Comment by smallzzy** [comment]
1. I was trying to understand what will happen if someone modify t1 while autotier is being used. I assumed that autotier requires the same folder structure. (If I understand it correctly, the rsync command that I used only copy over the folder structure). And that is why I am asking for more documentation.
2. I mount it as /home because t1 was originally /home. The diff on fstab was something like this.
```
-/dev/disk/by-uuid/46da36ee-d96a-435e-b58b-8e85d8420012 /home ext4 defaults 0 2
+/dev/disk/by-uuid/46da36ee-d96a-435e-b58b-8e85d8420012 /mnt/t1 ext4 defaults 0 2
+/dev/disk/by-uuid/76d28e01-5fbd-4eda-88b8-ba0ee4743d2c /mnt/t2 ext4 defaults 0 2
```
3. I was seeing the error when t1 has something in it + t2 has nothing + autotierfs has not crashed.
  1. if it crashed, it will report `Transport endpoint is not connected` instead.
4. I know that autotier is meant for tiered storage. In my case, t1 is an ssd and t2 is an hdd. I just do not know if autotier can handle if some file already exist on one tier.

**Comment by smallzzy** [comment]
I honestly do not see why autotierfs is not a superset vs something like mergefs. I seems to me that autotierfs is mergefs + files are re-distributed based on usage.
