### ISSUE TITLE
Question: Is autotier (fuse) file only?

### ISSUE THREAD

**Issue by thistleknot** [45Drives/autotier#44]
I defaulted to this because btier is over 8 years old and it won't compile.

I've read about ziggurat which is based on nova (they have some kernel builds including 5.1).  I got it to compile, but OL8 doesn't have sources for that linux version...  I still might be able to get to that though.

Anyways... I wanted to host things like databases and vm's as well on this tier system and when I realized it was file, I was like dang it.  I don't think that's going to work for me.  Not unless I can somehow create partial image files and construe them together (because it appears fuse/autotier is file based only, which makes sense now that I read what fuse is, user level)

**Comment by thistleknot** [comment]
I found lvmts, that looks promising

**Comment by joshuaboud** [comment]
Yes, autotier is only file based. I hope you find something that works out for you - but just a heads up, lvmts says it's deprecated in their github description and to use lvmcache instead.
