### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [45Drives/autotier#48]
Hey there,
    I came across this yesterday and it looked like exactly what I was hoping to find. I have a QNap TVS-951x with an SSD array and HDD array, but I just wasn't happy with the QNap software so I put TrueNAS Scale (Debian base using ZFS) on a NVME -> USB adapter and run the OS from there. 

Currently, I just have the same setup as I did prior, an SSD array and HDD array, but unlike the QNap software which had QTier, TrueNAS Scale doesn't have any sort of tiered storage. You will have to forgive me, storage/file systems are not my area of expertise, so I was wondering if you might know if there was any way to use this along with TrueNAS Scale and the two arrays that I have set up in there, or would it require more of a "blank slate" in order to do it's own configuration that would end up conflicting with TrueNAS?

Thanks,
-MH

**Comment by joshuaboud** [comment]
Hi,
Autotier is designed to take two or more filesystems and present them as a single filesystem. I have no experience with TrueNAS, but from what I could see online with a quick search, your arrays should be just ZFS arrays. There shouldn't be any issue with using autotier on top of two ZFS datasets. I haven't gotten around to doing much testing with setting up autotier where data is already present in the underlying tiers, but it should work as long as there are no conflicting files between the two tiers (files with the same path and name). Running `autotier oneshot` after mounting should be all it needs to do to get everything initialized. Keep in mind though that autotier is still in its preview phase, so experimenting with this setup is not entirely risk-free. If you do happen to have files "go missing", check around the underlying tiers for the files renamed to `.<filename>.autotier.hide`. These files will not show up in the mounted autotier filesystem, but will still be visible in the underlying tier with `ls -a`.

The .deb package for installation was packaged for Ubuntu 20.04, so I don't think it will install on Debian as some of the dependencies may be missing/too old. You can try your luck at installing from source, but you may end up needing to install RocksDB libraries from source as well. For reference for installing RocksDB from source, you can look at [my dockerfile for building in EL8](https://github.com/45Drives/autotier/blob/master/docker/el8).

**Comment by joshuaboud** [comment]
I just ran some tests with the current release, and if a file of the same name and path exist on both tiers, the file in the higher tier gets overwritten. I'll look into this further and make it so it doesn't overwrite any data on conflicting paths in a future version. Aside from that gotcha, as long as the file names are unique across the two tiers, your data should be safe.

**Comment by MostHated** [comment]
I appreciate the detailed reply. Much of my data is currently on my unraid server, as well as external drives. The system in which I want to run this is something of an "extra" system, which was why I was ok with running TrueNAS Scale on it, as that was just recently released as well. 

I don't currently have any overlapping data between the two datasets, so should be no worries there. 

I definitely will give this a go and report back how things work out. 👍

**Comment by joshuaboud** [comment]
I hope it works out well for you. Since the GCC version in Debian Buster is around 4.8, you will need to compile autotier with `make -j8 no-par-sort` when you get to that step to build using C++11 instead of C++17.

**Comment by MostHated** [comment]
Now that I think about it, you mentioned a dockerfile, is it possible to simply run this in docker and simply let it do it's thing from there?

**Comment by joshuaboud** [comment]
The dockerfiles I have are only used as an environment to build and package in for Ubuntu and RHEL8. It might be possible to set up a docker image to run autotier in. That sounds like it'd be a fun project to try out sometime. If you have any experience with writing dockerfiles, I would start with ubuntu:focal as a starting image and install the dependencies and wget the deb from the GitHub release to install. `/etc/autotier.conf`, the mountpoint, and all the tier paths would need to be mirrored into the container. The CLI tool `autotier` would have to be executed from within the container too since it needs to communicate with the filesystem daemon. I will add looking into creating a docker image to my TODO as well.

**Comment by MostHated** [comment]
I saw that a debian specific deb file has been added to the releases today. I spun up a debian VM so I could give the setup process a go and try to get used to it a bit, which I am about to do now, before I attempt installing it on my NAS. :+1:
