### ISSUE TITLE
[BUG] - Autotier has stopped responding and is utilizing 100% of a single core for over an hour now

### ISSUE THREAD

**Issue by somanysteves** [45Drives/autotier#52]
**Describe the bug**
Autotier has stopped responding and is utilizing 100% of a single core for over an hour now

**To Reproduce**
- Contents of /etc/autotier.conf
# autotier config
[Global]                       # global settings
Log Level = 1                  # 0 = none, 1 = normal, 2 = debug
Tier Period = 1000             # number of seconds between file move batches
Copy Buffer Size = 1 MiB       # size of buffer for moving files between tiers

[Tier 1]                       # tier name (can be anything)
Path = /media/ssd                         # full path to tier storage pool
Quota = 100%                        # absolute or % usage to keep tier under
# Quota format: x ( % | [K..T][i]B )
# Example: Quota = 5.3 TiB

[Tier 2]
Path = /media/hdd
Quota = 100%

# ... (add as many tiers as you like)

- Command/fstab entry used to mount
sudo crontab -eu root
@reboot autotierfs /media/pool -o allow_other,default_permissions

- Action that caused error
I think its because I ran oneshot and then tried to do other file operations

**Expected behavior**
filesystem is multithreaded and remains responsive

**Error Output**
If applicable, include any error messages shown, including output of `journalctl | grep autotierfs | grep -v "Tiering complete"`.

LOTS of these:
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.
May 21 23:34:34 tonga autotierfs[1957]: autotier already moving files.

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Fuse library version [`apt list --installed | grep fuse`]
fuse3/focal,now 3.9.0-2 amd64 [installed,automatic]
gvfs-fuse/focal,now 1.44.1-1ubuntu1 amd64 [installed,automatic]
libfuse2/focal,now 2.9.9-3 amd64 [installed,automatic]
libfuse3-3/focal,now 3.9.0-2 amd64 [installed,automatic]

 - Version [e.g. v1.1.3]
autotier 1.1.6

**Additional context**
Nope. Please let me know if there is anything else I can provide

**Comment by joshuaboud** [comment]
Hi,
First issue that's standing out is that your quota for the top tier is 100%. I would recommend keeping this quota below 95%. To fix the "autotier already moving files." issue, unmount the filesystem, delete `/var/lib/autotier/<some number>/autotier.lock`, and mount again. Let us know if this doesn't fix the issue. If `umount autotier` doesn't work for you, do a lazy unmount with `umount -l autotier` and then `killall -9 autotierfs`. Sometimes when autotier crashes it'll leave the lock file so when it's remounted, it'll think it's already running.
