### ISSUE TITLE
Feature request: Debian support

### ISSUE THREAD

**Issue by johnnyjosefsson** [45Drives/autotier#53]
Would you be willing to look into supporting Debian. With bullseye coming out (rc1 out now) in the next months most of the component are available with a "higher" version number that is now required to support autotier.

**Comment by joshuaboud** [comment]
[bullseye deb](https://github.com/45Drives/autotier/releases/download/v1.1.6/autotier_1.1.6-2bullseye_amd64.deb) (follow instructions in readme)
