### ISSUE TITLE
Unknown global field

### ISSUE THREAD

**Issue by jdmartinsF** [45Drives/autotier#55]
Hi,
I'm testing version 1.1.6-3.el8 and I get this warning
when use autotierfs:
"Warning: Unknown global field: Log Level = 1"
the parameter is misspelled? 

Thanks 
Jose

**Comment by joshuaboud** [comment]
Can you attach your full config file?

**Comment by jdmartinsF** [comment]
Hi,
Here is complete config file
[Global]                       # global settings
Log Level = 1                 # 0 = none, 1 = normal, 2 = debug
Tier Period = 60             # number of seconds between file move batches
Copy Buffer Size = 1 MiB       # size of buffer for moving files between tiers

[Tier 1]                       # tier name (can be anything)
Path = /shares/share1           # full path to tier storage pool
Quota = 1GiB                  # absolute or % usage to keep tier under

[Tier 2]
Path = /shares/share2
Quota = 90 %

The warning only happen if I use "-v" option, like this
"autotierfs -v /mnt/mount1 -o allow_other,default_permissions"

**Comment by joshuaboud** [comment]
Ah okay, the missing `-v` is why I didn't see it. I will look into this, thanks for bringing it up.

**Comment by joshuaboud** [comment]
Sorry for getting back so late. This has been fixed in commit 47be92e89e6c509086810d41b880817469a34cd0, but is not yet released. Still not sure why the old version was giving an error for log level as you did spell it properly, but the next release won't have that issue.
