### ISSUE TITLE
segfault with mergerfs

### ISSUE THREAD

**Issue by gojj-me** [45Drives/autotier#56]
**Describe the bug**
A bug or perhaps a incompatible or not intended usage for autotier. The autotierfs segfaults and stops when used with [mergerfs](https://github.com/trapexit/mergerfs) mountpoints

**To Reproduce**
- Contents of /etc/autotier.conf
# autotier config
[Global]                       # global settings
Log Level = 2                  # 0 = none, 1 = normal, 2 = debug
Tier Period = 900              # number of seconds between file move batches
Copy Buffer Size = 1 MiB       # size of buffer for moving files between tiers

[Tier 1]                       # tier name (can be anything)
Path = /mnt/ssd                # full path to tier storage pool
Quota = 3.1 TiB                    # absolute or % usage to keep tier under

[Tier 2]
Path = /mnt/hdd
Quota = 95 %

- Command/fstab entry used to mount
## mergerfs - fuse - SSD(s)
/mnt/shared/ssd/* /mnt/ssd fuse.mergerfs defaults,nonempty,dropcacheonclose=true,category.create=mfs,allow_other,use_ino,minfreespace=99G,fsname=mergerfs-ssd 0 0
## mergerfs - fuse - HDD(s)
/mnt/shared/hdd/* /mnt/hdd fuse.mergerfs defaults,nonempty,dropcacheonclose=true,category.create=mfs,allow_other,use_ino,minfreespace=99G,fsname=mergerfs-hdd 0 0
## autotierfs - fs / fuse over mergerfs SSD / HDD
/usr/bin/autotierfs /mnt/storage fuse allow_other,default_permissions 0 0

- Action that caused error
Activating/running autotier over two mergerfs mountpoints as tier1 and tier2

**Expected behavior**
Not to segfault, autotier mountpoint over/with mountpoints mergerfs-ssd as tier1 and mergerfs-hdd as tier2 and show/read/write data as autotier mountpoint and adhere to mergerfs filesystems mountpoints and managing of data within the tier.

**Error Output**
From: dmesg
[  210.949009] autotierfs[1757]: segfault at 0 ip 0000555c83864a7a sp 00007fcdb5b2ea70 error 4 in autotierfs[555c83829000+4e000]
[  210.949032] Code: 48 8b 84 24 80 00 00 00 48 8d 70 01 e8 ef 4c fc ff 41 80 7d 00 00 4c 8b 74 24 30 0f 85 6d 04 00 00 48 c7 44 24 58 00 00 00 00 <49> 8b 3e 49 89 ec 48 c7 44 24 60 00 00 00 00 48 c7 44 24 68 00 00

From: sudo mount -a
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::status: Transport endpoint is not connected: "/mnt/storage"
Aborted

**System (please complete the following information):**
 - OS: Debian Linux 11.0 (bullseye), amd64
 - autotier: autotier_1.1.6-3bullseye_amd64.deb
 - fuse
fuse3/now 3.10.3-1 amd64 [installed,local]
libfuse2/now 2.9.9-5 amd64 [installed,local]
libfuse3-3/now 3.10.3-1 amd64 [installed,local]
libfuse3-dev/now 3.10.3-1 amd64 [installed,local]

**Additional context**
The thought with the #53 was to autotier between a SSD and a HDD mountpoint/mergerfs system. The system has
1) several independent NAS systems
2) a "storage-merger-server" to mount the independent NAS systems to specific mountpoints /mnt/shared/ssd/* and /mnt/shared/hdd/*
3) the servers has mergerfs to make two mergerfs mountpoints mergersfs-ssd /mnt/ssd ==> /mnt/shared/ssd/* and mergerfs-hdd /mnt/hdd ==> /mnt/shared/hdd/*
4) the server has autotierfs to make one mounpoint for all storage which also autotiers between mergerfs-ssd and mergerfs-hdd

first mounted all NAS systems, then mergerfs mountpoints and then autotier - that did not really work as some folders seemed to be "duplicated - probably due to data existing in mountpoint at the first mount as described here #54 

unmounted everything and reset /var/lib/autotier/* - the mounting occured as (by uncomment fstab and run mount -a)
1) mount mergerfs-ssd/hdd mountpoint the same way, but without mounting the NAS system e.g. mountpoints was empty
2) mount autotier mountpoint the same way, over mountpoints mergerfs-ssd/hdd, and still not mounted NAS systems e.g. mountpoint still empty
3) mount NAS system for mergerfs-ssd for that mountpoint (which added ~4TB empty space for that mountpoint and accessible through autotierfs mountpoint - NAS system was at this time empty)
4) mount a single NAS system for mergerfs-hdd for that mountpoint (which added several more free and used TB sapce) for that mountpoint
5) was available through autotierfs mountpoint and no "duplicates" of folders was availabe --- but also no data was visible, for some time some folders and files become available through the autotier mountpoint

the autorier then segafault and also gave later on gave the filesystem error

so some of the answer in the post #54 could possible explain some of the issues/errors here, one could probably be that autotier not being to retrieve metadata for folders/files within the mergerfs mountpoint for possible several reasons e.g. fast enough, the mergerfs moving files within the own fuse filesystem space
-- however should not speculate to much here as outside my area of expertise and haven't found any data beyond the output error section indicating a specific problem.

**Comment by After-Shock** [comment]
@johnnyjosefsson 
Did you ever find a resolution to this issue/bug?

I'm experiencing this exact issue after a reboot running mergerfs in a similar fashion. SSD/HDD

**Comment by nsadlo** [comment]
I get this without mergefs. Just using a ZFS pool for a HDD tier and another pool for SSD tier.

**Comment by nsadlo** [comment]
Apr 30 17:49:18 HOSTNAME kernel: [  482.996117] autotierfs[89823]: segfault at 7f236e481413 ip 000055b13d691d38 sp 00007f24657f9770 error 4 in autotierfs[55b13d61e000+468000]
Apr 30 17:49:18 HOSTNAME kernel: [  482.996124] Code: 4e 08 49 89 c0 31 d2 48 63 c1 48 f7 f7 49 39 d2 0f 85 0e 05 00 00 48 89 f0 41 39 c9 75 d5 49 8b 00 48 85 c0 0f 84 fa 04 00 00 <4c> 8b 68 10 4c 8d 64 24 60 4c 8d 74 24 50 4c 89 64 24 50 4d 85 ed
Apr 30 18:18:32 HOSTNAME kernel: [ 2236.515196] autotierfs[221549]: segfault at 7f8c80a7b662 ip 000055b4e8fabd38 sp 00007f8bea9f9770 error 4 in autotierfs[55b4e8f38000+468000]
Apr 30 18:18:32 HOSTNAME kernel: [ 2236.515212] Code: 4e 08 49 89 c0 31 d2 48 63 c1 48 f7 f7 49 39 d2 0f 85 0e 05 00 00 48 89 f0 41 39 c9 75 d5 49 8b 00 48 85 c0 0f 84 fa 04 00 00 <4c> 8b 68 10 4c 8d 64 24 60 4c 8d 74 24 50 4c 89 64 24 50 4d 85 ed
Apr 30 18:28:03 HOSTNAME kernel: [ 2807.637678] pool-evolution-[24418]: segfault at 7fa9fffffff8 ip 00007faa54d9c47e sp 00007fa9f27fb970 error 4 in libc.so.6[7faa54d1f000+195000]
Apr 30 18:28:03 HOSTNAME kernel: [ 2807.637688] Code: 98 13 00 e8 04 b9 ff ff 0f 1f 40 00 f3 0f 1e fa 48 85 ff 0f 84 bb 00 00 00 55 48 8d 77 f0 53 48 83 ec 18 48 8b 1d 92 39 17 00 <48> 8b 47 f8 64 8b 2b a8 02 75 57 48 8b 15 18 39 17 00 64 48 83 3a
Apr 30 19:00:22 HOSTNAME kernel: [ 4746.627909] autotierfs[314140]: segfault at 7fc838ee6f99 ip 0000556eaa177de0 sp 00007fcfd67fb770 error 4 in autotierfs[556eaa104000+468000]
Apr 30 19:00:22 HOSTNAME kernel: [ 4746.627922] Code: 48 8b b3 10 01 00 00 31 d2 89 c7 48 98 48 f7 f6 48 8b 83 08 01 00 00 4c 8b 14 d0 49 89 d1 4d 85 d2 0f 84 44 04 00 00 49 8b 02 <8b> 48 08 39 cf 74 2b 4c 8b 00 4d 85 c0 0f 84 2e 04 00 00 41 8b 48

This keeps happening to me.

**Comment by johnnyjosefsson** [comment]
@After-Shock 
No, found no real solution for this so abandoned it for now/until a new version.
