### ISSUE TITLE
Deleted files cause abort

### ISSUE THREAD

**Issue by inthebrilliantblue** [45Drives/autotier#6]
Test running a minecraft server through samba on autotier, and I get missing file errors when manually running autotier.

Running on PopOs 19.10 x64 
autotier version 0.4-2

L1-nvme ssd mounted on /nvme
L2-sata ssd mounted on /ssd
L3-zfs raid10 hdd mounted on /tank/at

> scott@strike:~$ autotier
> autotier started.
> 
> terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>   what():  boost::filesystem::copy_file: No such file or directory: "/nvme/minecraft/red/plugins/dynmap/web/tiles/Aurella/t/-10_-1/zzzz_-304_-16.jpg", "/ssd/minecraft/red/plugins/dynmap/web/tiles/Aurella/t/-10_-1/zzzz_-304_-16.jpg"
> Aborted (core dumped)

**Comment by inthebrilliantblue** [comment]
Interestingly reinstalling boost on my system then recompiling the project leads to no errors. What version of boost would you recommend for this project?

**Comment by inthebrilliantblue** [comment]
Hrm, now getting

> Copying /nvme/minecraft/red/plugins/dynmap/web/tiles/Coria/ct/-1_0/zzzz_-32_0.jpg to /tank/at/minecraft/red/plugins/dynmap/web/tiles/Coria/ct/-1_0/zzzz_-32_0.jpg
> terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
>   what():  boost::filesystem::copy_file: File exists: "/nvme/minecraft/red/plugins/dynmap/web/tiles/Coria/ct/-1_0/zzzz_-32_0.jpg", "/tank/at/minecraft/red/plugins/dynmap/web/tiles/Coria/ct/-1_0/zzzz_-32_0.jpg"
> Aborted (core dumped)

**Comment by joshuaboud** [comment]
Hi, just added error handling while copying the files so if the file does not exist, the error is caught and reported but autotier continues along with the other files. This new feature is in v0.6.2-beta, with the relevant code in `void File::move()` in file.cpp.
