### ISSUE TITLE
Error while constructing socket server: Address already in use

### ISSUE THREAD

**Issue by After-Shock** [45Drives/autotier#61]
OS: Ubuntu 20.04 Server
Command used: sudo autotierfs /mnt/tierfs -o allow_other,default_permissions
Error: Error while constructing socket server: Address already in use

Not sure what port autotier uses but it would be nice to know in order to compare it to my netstat -an output.

Fresh install of Ubuntu server with just mergerfs on the server as well.  Not sure what socket/port autotier needs free?  Excited to get this working.

**Comment by joshuaboud** [comment]
Hi, autotier actually uses a Unix named socket which is just a file that exists on the filesystem. To try resolving this, check if any autotier processes are running with `ps aux | grep autotier` and kill them, and also remove the socket file after all processes are no longer running, which can be found in `/var/lib/autotier/<some string of numbers>/adhoc.socket`, then retry mounting.

**Comment by After-Shock** [comment]
That got it sorted, thank you for replying and your reply. Love everything you guys do.  Have a great weekend.
