### ISSUE TITLE
Autotierfs error

### ISSUE THREAD

**Issue by jm2307** [45Drives/autotier#62]
Hi 
After a long time, I was finally able to test the autotier again.
I installed version 1.2.0-1 EL8 rpm on a Rocky 8 distribution,
configured it with two tiers and everything went well.
Suddenly after a reboot every time I run the command
"autotierfs /shares/new/ -o allow_other,default_permissions"

I get this answer below and the volume does not mount.
"Error: Error while constructing socket server: Address already in use"
I've already reinstalled the software, deleted the volumes and created
 new ones and the problem remains.
I can't figure out what's going on, any help on this is highly appreciated.

Best regards
JDM

**Comment by dragon2611** [comment]
I don't remember exactly where (Maybe /var/lib/autotier) but there's a file somewhere that I had to delete it get it working again after an unclean shutdown.

**Comment by jm2307** [comment]
Hi,
Thanks for the tip
There is a folder inside /var/lib/autotier, inside that folder was
a file called "adhoc.socket", deleting that file solves the problem.
Thank you

**Comment by TheLinuxGuy** [comment]
> There is a folder inside /var/lib/autotier, inside that folder was
a file called "adhoc.socket", deleting that file solves the problem.

This should be part of the README.md - it fixed my problem too...
