### ISSUE TITLE
Feature Request / Check: Folder pinning

### ISSUE THREAD

**Issue by inthebrilliantblue** [45Drives/autotier#7]
So I know there is a way to pin files to certain tiers using the xattr user.autotier_pin on the file, but does it work on folders and their sub-files as well? Like say, I want every file in the folder "LARGE_FILES" which contains thousands of huge files to be pinned to the slowest but largest tier.

Testing this, I dont see those files staying on the slowest tier I pinned its root folder to.

Checking crawl.hpp, I only see code in class File checking for that xattr.

**Comment by joshuaboud** [comment]
The new releases of autotier implement command line tools for easier use of pinning. Read the readme for info on how to use them. Pinning a directory would complicate the algorithm for queuing up files, but this may be added in a future release. With the current release, to pin all files recursively in a directory run:  
`find <directory path> -type f -print | xargs autotier pin "<tier name>"`  
and to unpin files from a directory:  
`find <directory path> -type f -print | xargs autotier unpin`
