### ISSUE TITLE
Pinning files does nothing.

### ISSUE THREAD

**Issue by inthebrilliantblue** [45Drives/autotier#8]
**OS:** PopOs 19.10 x64
**Tier1:** SATA SSD 120GB at /t1
**Tier2:** SATA HDD 8TB at /t2

**Problem:**
When setting xattr of user.autotier_pin = /t2 to move file to slower tier, the file doesnt move out of /t1.

I added some code to my local copy of autotier to output this:

OldPath: /t1/ebooks/random.pdf
NewPath: /t1/ebooks/random.pdf
SymLink: /t1/ebooks/random.pdf
UserPin: /t2

**Steps to replicate:**
Load tiers with enough files to trigger moves between tiers on normal usage.
Find file to set user.autotier_pin = /t2
Access file in some way to change last_atime.
Run ./autotier.
Check /t1 for symlink.

**Comment by joshuaboud** [comment]
Hi, thanks for the feedback. This feature was overlooked while refactoring the code, it is present now. Let us know if there are any further issues regarding pinning.
